CREATE TABLE IF NOT EXISTS public.tour (
	id serial NOT NULL,
	destinations text NOT NULL,
	normaladultprice DECIMAL(19, 4) NOT NULL,
	normalchildprice DECIMAL(19, 4) NOT NULL,
	holidayadultprice DECIMAL(19, 4) NOT NULL,
	holidaychildprice DECIMAL(19, 4) NOT NULL,
	holidays text NOT NULL,
	isdailytour bool NOT NULL,
	vehicleservices text NOT NULL,
	departurelocation text NOT NULL,
	descriptions text NULL,
	maxpassenger int4 NULL,
	cancellationpolicy text NOT NULL,
	surchargepolicy text NULL,
	note text NULL,
	programs text NULL,
	includeservices text NOT NULL,
	dateoff text NULL,
	isactive bool NOT NULL DEFAULT true,
	createdat timestamptz DEFAULT CURRENT_TIMESTAMP,
	updatedat timestamptz DEFAULT CURRENT_TIMESTAMP,
	deletedat timestamptz NULL,
	locationid int4 NOT NULL,
	serviceid int4 NOT NULL,
	pickupdropofflocation jsonb NULL,
	totaltourtime jsonb NULL,
	CONSTRAINT tour_pkey PRIMARY KEY (id)
);
