CREATE TABLE IF NOT EXISTS public.stay (
	id serial NOT NULL,
	name text NOT NULL,
	accommodationtypeid int4 NULL,
	introduction text NULL,
	acreage text NULL,
	numberofbedroom int4 NULL,
	numberofbed int4 NULL,
	numberofsinglebed int4 NULL,
	numberofdoublebed int4 NULL,
	numberoflargedoublebed int4 NULL,
	numberoflargebed int4 NULL,
	numberofsuperlargebed int4 NULL,
	numberofmattress int4 NULL,
	numberofsofa int4 NULL,
	numberofbunk int4 NULL,
	numberofbathroom int4 NULL,
	numberofprivatebathroom int4 NULL,
	numberofsharedbathroom int4 NULL,
	numberofkitchen int4 NULL,
	numberofprivatekitchen int4 NULL,
	numberofsharedkitchen int4 NULL,
	amenities jsonb NULL,
	facilities jsonb NULL,
	rules jsonb NULL,
	mediacontentids jsonb NULL,
	currencyid int4 NULL,
	numberofstandardguest int4 NULL,
	maxnumberofguest int4 NULL,
	numberofadult int4 NULL,
	numberofchild int4 NULL,
	numberofinfant int4 NULL,
	maxguestincludechildandinfant bool DEFAULT true,
	price DECIMAL(19, 4) NULL,
	priceweekend DECIMAL(19, 4) NULL,
	feeincreaseadult DECIMAL(19, 4) NULL,
	feeincreasechild DECIMAL(19, 4) NULL,
	feeincreaseinfant DECIMAL(19, 4) NULL,
	feecleaning DECIMAL(19, 4) NULL,
	discountweeklyrental DECIMAL(19, 4) NULL,
	discountmonthlyrental DECIMAL(19, 4) NULL,
	discountyearlyrental DECIMAL(19, 4) NULL,
	discountearlybooking DECIMAL(19, 4) NULL,
	discountlasthourbooking DECIMAL(19, 4) NULL,
	discountearlybookingday int4 NULL,
	discountlasthourbookingtime text NULL,
	status text NULL,
	createdat timestamptz DEFAULT CURRENT_TIMESTAMP,
	updatedat timestamptz DEFAULT CURRENT_TIMESTAMP,
	deletedat timestamptz NULL,
	serviceid int4 NOT NULL,
	CONSTRAINT stay_pkey PRIMARY KEY (id)
);
