CREATE TABLE IF NOT EXISTS public.stayreservation (
	id serial NOT NULL,
	price DECIMAL(19, 4) NOT NULL,
	numadult int4 NOT NULL,
	numchildren int4 NOT NULL,
  numinfant int4 NOT NULL,
	currencyid int4 NOT NULL,
	note text NULL,
	purposetrip text NULL,
  expectedcheckintime text NOT NULL,
	reservationcode text NOT NULL,
	userinfo jsonb NULL,
  otheruserinfo jsonb NULL,
	stayid int4 NOT NULL,
	startdate timestamptz NOT NULL,
	enddate timestamptz NULL,
	metadata jsonb NULL,
	createdat timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	updatedat timestamptz NULL DEFAULT CURRENT_TIMESTAMP,
	deletedat timestamptz NULL,
	bookingid int4 NOT NULL,
	CONSTRAINT stay_reservation_pkey PRIMARY KEY (id),
	CONSTRAINT uique_stay_reservation_code UNIQUE (reservationcode),
  CONSTRAINT uique_booking_id UNIQUE (bookingid)
);