export const FOLLOW_STATUS_REQUESTED = 'REQUESTED';
export const FOLLOW_STATUS_ACCEPTED = 'ACCEPTED';
export const FOLLOW_STATUS = [FOLLOW_STATUS_REQUESTED, FOLLOW_STATUS_ACCEPTED];

export const HAVE_BEEN_FOLLOWING = "YOU'VE_BEEN_FOLLOWING_THIS_PERSON_ALREADY";
export const HAVE_NOT_FOLLOWED = 'YOU_HAVE_NOT_FOLLOWED_THIS_PERSON';
export const HAS_NOT_FOLLOWED_YOU = 'THIS_PERSON_HAS_NOT_FOLLOWED_YOU_YET';
