import {USER_GENDER_FEMALE, USER_GENDER_MALE} from './user-constants';
import {PageTypesEnum} from './page-constant';

export const MEDIA_CONTENT_TYPE_CLONE = 'CLONE';
export const MEDIA_CONTENT_TYPE_UPLOAD = 'UPLOAD';
export const MEDIA_CONTENT_TYPE_SYSTEM = 'SYSTEM';
export const MEDIA_CONTENT_TYPE_SYSTEM_BACKGROUND_POST = 'SYSTEM_BACKGROUND_POST';
export const MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_FOOD = 'SYSTEM_BACKGROUND_DEFAULT_PAGE_FOOD';
export const MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_STAY = 'SYSTEM_BACKGROUND_DEFAULT_PAGE_STAY';
export const MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_TOUR = 'SYSTEM_BACKGROUND_DEFAULT_PAGE_TOUR';
export const MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_FOOD = 'SYSTEM_AVATAR_DEFAULT_PAGE_FOOD';
export const MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_STAY = 'SYSTEM_AVATAR_DEFAULT_PAGE_STAY';
export const MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_TOUR = 'SYSTEM_AVATAR_DEFAULT_PAGE_TOUR';

export const SYSTEM_MEDIA_CONTENT_DEFAULT_AVATAR_CUSTORM_USER_ID = 1;
export const SYSTEM_MEDIA_CONTENT_DEFAULT_AVATAR_WOMEN_USER_ID = 2;
export const SYSTEM_MEDIA_CONTENT_DEFAULT_AVATAR_MEN_USER_ID = 3;
export const SYSTEM_MEDIA_CONTENT_DEFAULT_BACKGROUND_USER_ID = 4;

export const SYSTEM_MEDIA_CONTENT_RESOURCE_TYPE_IMAGE = 'IMAGE';
export const SYSTEM_MEDIA_CONTENT_RESOURCE_TYPE_VIDEO = 'VIDEO';
export const SYSTEM_MEDIA_CONTENT_RESOURCE_TYPES = [
  SYSTEM_MEDIA_CONTENT_RESOURCE_TYPE_IMAGE,
  SYSTEM_MEDIA_CONTENT_RESOURCE_TYPE_VIDEO,
];

export const BgDefaultPage = {
  [String(PageTypesEnum.food)]: MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_FOOD,
  [String(PageTypesEnum.stay)]: MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_STAY,
  [String(PageTypesEnum.tour)]: MEDIA_CONTENT_TYPE_BG_DEFAULT_PAGE_TOUR,
};

export const AvatarDefaultPage = {
  [String(PageTypesEnum.food)]: MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_FOOD,
  [String(PageTypesEnum.stay)]: MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_STAY,
  [String(PageTypesEnum.tour)]: MEDIA_CONTENT_TYPE_AVATAR_DEFAULT_PAGE_TOUR,
};

export enum SystemDefaultAvatarMediaTypeEnum {
  male = 'SYSTEM_DEFAULT_AVATAR_MEN',
  female = 'SYSTEM_DEFAULT_AVATAR_WOMEN',
  unspecified = 'SYSTEM_DEFAULT_AVATAR_CUSTORM',
}
export function SYSTEM_DEFAULT_AVATARS(gender: string) {
  if (gender === USER_GENDER_MALE) {
    return SystemDefaultAvatarMediaTypeEnum.male;
  } else {
    if (gender === USER_GENDER_FEMALE) {
      return SystemDefaultAvatarMediaTypeEnum.female;
    }
  }
  return SystemDefaultAvatarMediaTypeEnum.unspecified;
}
