export const MYMAP_TYPE_SAVED = 'SAVED';
export const MYMAP_TYPE_HAD_CAME = 'HAD_CAME';
export const MYMAP_TYPE_WISH_CAME = 'WISH_CAME';
export const MYMAP_TARGET_TYPE_LOCATION = 'LOCATION';
export const MYMAP_TARGET_TYPE_OTHER = 'OTHER';
export function MY_MAP_TYPES() {
  return [MYMAP_TYPE_SAVED, MYMAP_TYPE_HAD_CAME, MYMAP_TYPE_WISH_CAME];
}
export function MY_MAP_TARGET_TYPES() {
  return [MYMAP_TARGET_TYPE_LOCATION, MYMAP_TARGET_TYPE_OTHER];
}

export const MYMAP_ACCESS_TYPE_PUBLIC = 'PUBLIC';
export const MYMAP_ACCESS_TYPE_PRIVATE = 'PRIVATE';
export const MYMAP_ACCESS_TYPE_FOLLOW = 'FOLLOW';
export const MYMAP_ACCESS_TYPE = [MYMAP_ACCESS_TYPE_PUBLIC, MYMAP_ACCESS_TYPE_PRIVATE, MYMAP_ACCESS_TYPE_FOLLOW];
