export const TASK_TYPE_WHERE = 'WHERE';
export const TASK_TYPE_FOOD = 'FOOD';
export const TASK_TYPE_STAY = 'STAY';
export const TASK_TYPE_TOUR = 'TOUR';
export const TASK_TYPES = [TASK_TYPE_WHERE, TASK_TYPE_FOOD, TASK_TYPE_STAY, TASK_TYPE_TOUR];
export const TASK_STATUS_COMPLETED = 'COMPLETED';
export const TASK_STATUS_INCOMPLETE = 'INCOMPLETE';
export const TASK_STATUS = [TASK_STATUS_COMPLETED, TASK_STATUS_INCOMPLETE];
