export const POST_ACCESS_TYPE_PRIVATE = 'PRIVATE';
export const POST_ACCESS_TYPE_PUBLIC = 'PUBLIC';
export const POST_ACCESS_TYPE_FOLLOW = 'FOLLOW';
export const POST_ACCESS_TYPES = [POST_ACCESS_TYPE_PRIVATE, POST_ACCESS_TYPE_PUBLIC, POST_ACCESS_TYPE_FOLLOW];

export const MEDIA_PREVIEW_TYPES_VIDEO = 'VIDEO';
export const MEDIA_PREVIEW_TYPES_IMAGE = 'IMAGE';
export const MEDIA_PREVIEW_TYPES_NONE = 'NONE';
export const MEDIA_PREVIEW_TYPES = [MEDIA_PREVIEW_TYPES_VIDEO, MEDIA_PREVIEW_TYPES_IMAGE, MEDIA_PREVIEW_TYPES_NONE];

export const POST_TYPE_CREATED = 'CREATED';
export const POST_TYPE_ACTIVITY = 'ACTIVITY';
export const POST_TYPE_SHARED = 'SHARED';
export const POST_TYPE_PAGE = 'PAGE_NEW';
export const POST_TYPE_SERVICE = 'SERVICE';
export const POST_TYPE_PAGE_REVIEW = 'PAGE_REVIEW';
export const POST_TYPE_MY_MAP = 'MY_MAP';
export const POST_TYPE_SHARE_PLAN = 'SHARE_PLAN';
export const POST_TYPE_SERVICE_REVIEW = 'SERVICE_REVIEW';

export const POST_TYPES = [
  POST_TYPE_CREATED,
  POST_TYPE_SHARED,
  POST_TYPE_ACTIVITY,
  POST_TYPE_PAGE,
  POST_TYPE_SERVICE,
  POST_TYPE_PAGE_REVIEW,
  POST_TYPE_MY_MAP,
  POST_TYPE_SHARE_PLAN,
  POST_TYPE_SERVICE_REVIEW,
];
export const POST_SEARCH_MODE_SYSTEM = 'SYSTEM';
export const POST_SEARCH_MODE_COMUNITY = 'COMUNITY';
export const POST_SEARCH_MODE_FOLLOW = 'FOLLOW';
export const POST_SEARCH_MODES = [POST_SEARCH_MODE_SYSTEM, POST_SEARCH_MODE_COMUNITY, POST_SEARCH_MODE_FOLLOW];

export const SEARCH_TYPE_COMMUNITY_LOCATION = 'LOCATION';
export const SEARCH_TYPE_COMMUNITY_POST = 'POST';
export const SEARCH_TYPE_COMMUNITY = [SEARCH_TYPE_COMMUNITY_LOCATION, SEARCH_TYPE_COMMUNITY_POST];

export enum PostStatusEnum {
  draft = 'DRAFT',
  public = 'PUBLIC',
}
