export const RANKING_ACCESS_TYPE_ACCEPTED = 'ACCEPTED';
export const RANKING_ACCESS_TYPE_NOT_ACCEPTED = 'NOT_ACCEPTED';
export const RANKING_ACCESS_TYPES = [RANKING_ACCESS_TYPE_ACCEPTED, RANKING_ACCESS_TYPE_NOT_ACCEPTED];
export const RANKING_TYPE_RANKING_LOCATION = 'RANKING_LOCATION';
export const RANKING_TYPE_RANKING_POST = 'RANKING_POST';
export const RANKING_TYPE_RANKING_PAGE = 'RANKING_PAGE';
export const RANKING_TYPE_RANKING_SERVICE = 'RANKING_SERVICE';
export const RANKING_TYPES = [
  RANKING_TYPE_RANKING_LOCATION,
  RANKING_TYPE_RANKING_POST,
  RANKING_TYPE_RANKING_PAGE,
  RANKING_TYPE_RANKING_SERVICE,
];
